source = /home/cjcocokrisp/.cache/wal/colors-hyprland.conf

$user=echo "$USER@$(cat /etc/hostname)"
$font = SourceCodePro


general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%I")"
    color = $color15
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 150
    font_family = $font
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = $color15
    font_size = 150
    font_family = $font
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = $color15
    font_size = 14
    font_family = $font
    position = 0, -130
    halign = center
    valign = center
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 2
    outer_color = $color10
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(12, 12, 29, 0.5)
    check_color = $color5
    font_color = $color15
    fail_color = rgba(233, 61, 88, 255)
    font-family = $font
    fade_on_empty = true
    placeholder_text =<i>Password</i>
    hide_input = false
    position = 0, -220
    halign = center
    valign = center
    zindex = 20
}

# USER
label {
    monitor =
    text = cmd[update:60000] $user
    color = $color15
    font_size = 14
    font_family = SourceCodePro
    position = 0, -160
    halign = center
    valign = center
}

background {
    monitor =
    path = screenshot
    blur_passes = 2 
}#
