###################
### PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus --new-window
$menu = ~/.config/rofi/launchers/type-1/launcher.sh
$lock = hyprlock
$chat = Discord
$games = steam
$browser = zen-browser
$bluetooth = blueman-manager
$bluetoothDaemon = blueman-applet
$wifiDaemon = nm-applet --indicator
$dashboard = ~/scripts/eww-open-close.sh dashboard
$screenshotRegion = hyprshot -m region -o ~/Pictures/Screenshots
$screenshotWindow = hyprshot -m window -o ~/Pictures/Screenshots
$screenshotFull = hyprshot -m output -o ~/Pictures/Screenshots
$monitor = btop
$notifications = mako
$widgets = eww daemon
$statusBar = waybar
